export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const RESET_CHARACTERS = 'RESET_CHARACTERS';

export const FILTER_TYPE = 'FILTER_TYPE';
export const FILTER_API = 'FILTER_API';
export const ORDER_ALPHABET = 'ORDER_ALPHABET';
export const ORDER_ATTACK = 'ORDER_ATTACK ';
export const ERROR = 'ERROR';

// export const FILTER_POKEMON = 'FILTER_POKEMON';
// export const ORDER_POKEMON = 'ORDER_POKEMON';